
export const POST_REQUEST_PENDING = "POST_REQUEST_PENDING";
export const POST_REQUEST_FAILURE = "POST_REQUEST_FAILURE";

//GET POST
export const GET_QUESTION_REQUEST_SUCCESS = "GET_POST_REQUEST_SUCCESS";

//POST POST
export const POST_ANSWER_REQUEST_SUCCESS = "POST_POST_REQUEST_SUCCESS";

// Score API
export const POST_SCORE_LOADING = "POST_SCORE_LOADING";
export const POST_SCORE_SUCCESS = "POST_SCORE_SUCCESS";
export const POST_SCORE_FAILURE = "POST_SCORE_FAILURE";



